### ISSUE TITLE
Oak Item Optimization ignores challenges

### ISSUE THREAD

**Issue by Durzaofshades** [Farigh/pokeclicker-automation-desktop#15]
When I enable Oak item optimization while having the no click challenge enabled, the automation continues to try to put the rock Helmet into my loadout even when I cannot click

**Comment by Farigh** [comment]
This should have been addressed by Farigh/pokeclicker-automation#91

If the problem still persist, please create an issue there instead.
This repository is only dedicated to the Desktop app.
