### ISSUE TITLE
Ephenia Autoclicker Freeze

### ISSUE THREAD

**Issue by NAFEDUDE** [Farigh/pokeclicker-automation-desktop#22]
Using [Ephenia's autoclicker script](https://github.com/Ephenia/Pokeclicker-Scripts/blob/master/enhancedautoclicker.user.js) causes the game to hang on load. I have already changed the final lines myself, and it does this even if every other script is turned off.

![image](https://github.com/Farigh/pokeclicker-automation-desktop/assets/32426052/965af9c1-c4ec-4a48-81c5-1fd84cc20916)

**Comment by Farigh** [comment]
Hi,

It seems to be a problem on Ephonia's script side.
![image](https://github.com/Farigh/pokeclicker-automation-desktop/assets/11090416/d57387a2-52b7-4f10-b6f8-42f6bf5e673e)

It's looking for a variable that was never defined.
This variable is not part of the game either : 
![image](https://github.com/Farigh/pokeclicker-automation-desktop/assets/11090416/7e438e3b-5560-47f2-aca7-2eb738fc93c5)

In general, I'm not in charge of maintaining those external scripts, thus any issues with those should be reported on their author's repository

**Comment by Farigh** [comment]
I changed the code evaluation method via #23 
This new method is more secure and is less strict on JS syntaxe, which should address your problem

The update should dispatch automatically to your system, once merged

**Comment by NAFEDUDE** [comment]
Hey! Sorry if I caused any trouble. It was such an odd issue I honestly didn't know who to contact, since it wasn't throwing an error to me at all, the game basically softlocked upon launch. Thank you for looking into it on the end of your scripts; if issues persist I will inform Ephenia. I was able to manually fix the other reported bug on those scripts and even submitted a merge request on their end to fix it.

**Comment by Farigh** [comment]
No problem at all.

The problem was due to the lack of compliance with strict JavaScript declaration.
It's still an issue on Ephenia's scripts side but most modern browser fix those problems silently.

It allowed me to use a more secured and performant method so I'm glad this pushed me into looking into it.

**Comment by NAFEDUDE** [comment]
I was going to say, it seemed like it was still a benefit in the end to bring it up here. I'm glad it worked out that way. Thanks again!
