### ISSUE TITLE
UI zoomed out

### ISSUE THREAD

**Issue by FolkPunkDruid** [Farigh/pokeclicker-automation-desktop#33]
I figured out that in the desktop app, using the [ctrl -] shortcut to zoom out works, but using [ctrl +] to zoom back in doesn't work. I tried looking through the settings menus for anything about zooming, but I can barely read the text with how far zoomed out everything is. It's making the game unplayable 

### Solutions I've tried
- Uninstalling and re-installing the desktop app
- Uninstalling the desktop app, restarting my computer, and reinstalling
- Loading default settings
- Installing Vanilla Pokeclicker, and zooming in using that (zooming didn't work at all)

Any ideas on how to fix this? I can't play the game on desktop like this.

**Comment by Farigh** [comment]
Their seem to have a few issues with zoom in electron apps.

Based on [this comment](https://github.com/electron/electron/issues/29996#issuecomment-2056658337), you might want to try `Ctrl+Shift+-` or `Ctrl+Shift+0`

**Comment by FolkPunkDruid** [comment]
> Their seem to be a few issues with zoom in electron apps.
> 
> Based on [this comment](https://github.com/electron/electron/issues/29996#issuecomment-2056658337), you might want to try `Ctrl+Shift++` or `Ctrl+Shift+0`
 that worked, thanks so much!

**Comment by FolkPunkDruid** [comment]
> Their seem to be a few issues with zoom in electron apps.
> 
> Based on [this comment](https://github.com/electron/electron/issues/29996#issuecomment-2056658337), you might want to try `Ctrl+Shift++` or `Ctrl+Shift+0`

that worked, thanks so much!
