### ISSUE TITLE
wanted to add a new script

### ISSUE THREAD

**Issue by GebtName** [Farigh/pokeclicker-automation-desktop#35]
Hey, (the guy from reddit lol)

i tried to add a script (https://github.com/Ephenia/Pokeclicker-Scripts/blob/master/custom/oakitemsunlimited.user.js this one for example) and copied the whole script into it but it didnt changed anything maybe im doing smth wrong or it just doesnt work for some reason tried other scripts from this site and they all didnt worked it also says 2/2 scripts are active but yea like i said it didnt change anything 

hope it helps somehow if you need smth let me know ill try to help

**Comment by Farigh** [comment]
Hi, 

Have you tried the solution provided in the pinned issue : #20 ?

**Comment by GebtName** [comment]
omg your a goat holy yea no i didnt saw the pinned issue im not really imo github is really confusing if you dont really look into it and dont know anything about coding hahah but it helped your the best thank you
